### ISSUE TITLE
I need code for hollow diamond code in python

### ISSUE THREAD

**Issue by SivaPullaiah** [SivaPullaiah/How-to-run-python#2]
![Image](https://user-images.githubusercontent.com/93705673/212714193-a1e4b650-9b05-4386-b670-530c1567a23f.png)

**Comment by sivapullaiahmangali** [comment]
I know that exact code

**Comment by sivapullaiahmangali** [comment]
Can you provide that,
I will review that

**Comment by SivaPullaiah** [comment]
Okay then send me that code,
I will merg it

**Comment by sivapullaiahmangali** [comment]
'''See GET HELP you can get more clarity'''
n=int(input())
print(' '*(n-1)+'*')
holl_count=-1
for each in range(1,n):
    spaces=' '*(n-each-1)
    holl_count+=2
    hollow=' '*(holl_count-1)
    print(spaces+'* '+hollow+'*')
for each in range(1,n-1):
    spaces=' '*each
    holl_count-=2
    hollow=' '*(holl_count-1)
    print(spaces+'* '+hollow+'*')
print(' '*(n-1)+'*')``

**Comment by sivapullaiahmangali** [comment]
@SivaPullaiah 
Is that code ok

**Comment by SivaPullaiah** [comment]
Yeah it's working properly
Thanks
